name: 'Mass Issue Action'
description: 'Creates an issue on Repositories X,Y,Z (repositories defined by (in this case .env) files in Repository A)'
author: 'Jacob Haitsma'

inputs:
  USER_ACCESS_TOKEN:
    description: 'Github User Access Token'
    required: true
  actor:
    description: 'The initiator of the action'
    required: true
  issue_title:
    description: 'Title of the issue to be filed'
    required: true
  issue_body:
    description: 'Body of the issue to be filed'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'