name: Mass Issue

on:
  workflow_dispatch:
    inputs:
      issue_title:
        description: 'Issue Title'
        required: true
      issue_body:
        description: 'Issue Body'
        required: false

jobs:
  mass_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
          actor: ${{ github.actor }}
          issue_title: ${{ github.event.inputs.issue_title }}
          issue_body: ${{ github.event.inputs.issue_body }}
