name: Mass Issue

on:
  workflow_dispatch:
    inputs:
      issue_title:
        description: 'Issue Title'
        required: true
      issue_body:
        description: 'Issue Body'
        required: true

jobs:
  mass_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          MACHINE_WORKER_TOKEN: ${{secrets.MACHINE_WORKER_TOKEN}}
